
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 23;
  public static final int mayoroigual = 17;
  public static final int masmas = 19;
  public static final int imprime = 4;
  public static final int fin_sent = 6;
  public static final int por = 10;
  public static final int menoroigual = 18;
  public static final int menos = 9;
  public static final int menor = 15;
  public static final int inicio = 2;
  public static final int entre = 11;
  public static final int real = 21;
  public static final int igual = 16;
  public static final int EOF = 0;
  public static final int abrepar = 12;
  public static final int variable = 20;
  public static final int error = 1;
  public static final int asigna = 5;
  public static final int entero = 22;
  public static final int fin = 3;
  public static final int masigual = 7;
  public static final int cierrapar = 13;
  public static final int mas = 8;
  public static final int mayor = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "inicio",
  "fin",
  "imprime",
  "asigna",
  "fin_sent",
  "masigual",
  "mas",
  "menos",
  "por",
  "entre",
  "abrepar",
  "cierrapar",
  "mayor",
  "menor",
  "igual",
  "mayoroigual",
  "menoroigual",
  "masmas",
  "variable",
  "real",
  "entero",
  "cadena"
  };
}

